name: linkos_sdk
description: "Link-OS Multiplatform SDK for Dart/Flutter"
version: 0.0.1
homepage: https://github.com/shigomany/linkos_sdk.git

platforms:
  android:
  ios:

topics:
  - printers
  - zebra
  - pigeon

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^16.0.4
  build_runner: ^2.4.8
  pigeon_build_runner: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.linkos_sdk
        pluginClass: LinkosSdkPlugin
      ios:
        pluginClass: LinkosSdkPlugin
      linux:
        pluginClass: LinkosSdkPlugin
      macos:
        pluginClass: LinkosSdkPlugin
      windows:
        pluginClass: LinkosSdkPluginCApi

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
pigeon:
  # main-input defines default values and base paths or package names
  main-input:
    input: pigeons/
    dart:
      out: lib/src/pigeons/ 
      test-out: test/pigeons/
    swift:
      out: ios/Runner/
    kotlin:
      out: android/src/main/kotlin/com/plugin/linkos_sdk
      package: com.plugin.linkos_sdk
    cpp:
      header-out: windows/runner
      source-out: windows/runner
      namespace: LinkOs

  inputs:

    - input: printer_api.dart
      dart:
        out: printer_api.dart
      kotlin:
        out: printer/IPrinterAPI.kt
        package: .printer

    - input: network_discovery_printers_api.dart
      dart:
        out: network_discovery_printers_api.dart
      kotlin:
        out: discovery/INetworkDiscoveryPrintersAPI.kt
        package: .discovery
